
### Login
POST http://localhost/api/login HTTP/1.1
content-type: application/json

{
    "email": "user@email.com",
    "password": "12345678"
}

### Test API User Information
GET http://localhost/api/user HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmUzMTc0NmRkNThmMDMzMzM3ZWEwNWI2MGFjZGQyYmUxZjgxMzIyZDAzZWE2MWYzOWM4ZDNiODMyMDA5OWRhOGQzOTBkMjQ3OWQ5MjM4YjMiLCJpYXQiOjE2MDM0OTkyNzQsIm5iZiI6MTYwMzQ5OTI3NCwiZXhwIjoxNjM1MDM1Mjc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.W162AGQVxgZMEJySJFycs1Ncjm9GQCTjQpo9PEn-iYKrUIeRrTBYSBc3KKvswBl5lAEu6qNIhGRDV6saO7RBM0JqBKn1ZvlBdkhGcvEq5EwoLUEHmUin99EqAnXSV0IROGviwzISLCUIa3PMxG0NcdfC_WfyoY0KHc5X68lIUnzfwZGp2rfmQRrps57Ea6RiwxF1eheFqBBu1PbNz0dqob04HA56ZA84Ag6j0sJiJRPaRUy7zFi_ZGAnSgDOoE_MvXKM8u82qBAS04L5EOR2P0cfYjO3W9sCveyV4dRkajVcVF0jTlcpd0UeaUbuJrhNFfCEoJU2zCDCztqDWGmsOAJCZG-v14cwCDb8sjSk9lqPf6GvQ8OKv8-jcgb5u2v4oVUFawECOkgQVojZ7RGYRx2R9CKdjdF03qspJIDGtEEb3KV98oryCaHpnYQemoG-Z-yKpBYP4NGVLbAG3x1XpdJCF7RFUJz5_nM0BGMnJGZIHyMEoqBjZnB4xSJat3zvTKfZqhjZ_MncIu6DlvjVWKPbrhk-HFZ0bJPbLeJbbnYaziWwUt89w6-Prt80N2p9r5QlelhKDsqupTB9mV41Pn5z43WlXeYODJThvvObDlKal2vlk-xD3nTQT9V1TYoFljTtleaMMHAHsA3O-MjCHgG0Ig3CszcNNqlV-SU2Si4

### Users
GET http://localhost/api/users HTTP/1.1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmUzMTc0NmRkNThmMDMzMzM3ZWEwNWI2MGFjZGQyYmUxZjgxMzIyZDAzZWE2MWYzOWM4ZDNiODMyMDA5OWRhOGQzOTBkMjQ3OWQ5MjM4YjMiLCJpYXQiOjE2MDM0OTkyNzQsIm5iZiI6MTYwMzQ5OTI3NCwiZXhwIjoxNjM1MDM1Mjc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.W162AGQVxgZMEJySJFycs1Ncjm9GQCTjQpo9PEn-iYKrUIeRrTBYSBc3KKvswBl5lAEu6qNIhGRDV6saO7RBM0JqBKn1ZvlBdkhGcvEq5EwoLUEHmUin99EqAnXSV0IROGviwzISLCUIa3PMxG0NcdfC_WfyoY0KHc5X68lIUnzfwZGp2rfmQRrps57Ea6RiwxF1eheFqBBu1PbNz0dqob04HA56ZA84Ag6j0sJiJRPaRUy7zFi_ZGAnSgDOoE_MvXKM8u82qBAS04L5EOR2P0cfYjO3W9sCveyV4dRkajVcVF0jTlcpd0UeaUbuJrhNFfCEoJU2zCDCztqDWGmsOAJCZG-v14cwCDb8sjSk9lqPf6GvQ8OKv8-jcgb5u2v4oVUFawECOkgQVojZ7RGYRx2R9CKdjdF03qspJIDGtEEb3KV98oryCaHpnYQemoG-Z-yKpBYP4NGVLbAG3x1XpdJCF7RFUJz5_nM0BGMnJGZIHyMEoqBjZnB4xSJat3zvTKfZqhjZ_MncIu6DlvjVWKPbrhk-HFZ0bJPbLeJbbnYaziWwUt89w6-Prt80N2p9r5QlelhKDsqupTB9mV41Pn5z43WlXeYODJThvvObDlKal2vlk-xD3nTQT9V1TYoFljTtleaMMHAHsA3O-MjCHgG0Ig3CszcNNqlV-SU2Si4

### User by ID
GET http://localhost/api/users/1 HTTP/1.1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmUzMTc0NmRkNThmMDMzMzM3ZWEwNWI2MGFjZGQyYmUxZjgxMzIyZDAzZWE2MWYzOWM4ZDNiODMyMDA5OWRhOGQzOTBkMjQ3OWQ5MjM4YjMiLCJpYXQiOjE2MDM0OTkyNzQsIm5iZiI6MTYwMzQ5OTI3NCwiZXhwIjoxNjM1MDM1Mjc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.W162AGQVxgZMEJySJFycs1Ncjm9GQCTjQpo9PEn-iYKrUIeRrTBYSBc3KKvswBl5lAEu6qNIhGRDV6saO7RBM0JqBKn1ZvlBdkhGcvEq5EwoLUEHmUin99EqAnXSV0IROGviwzISLCUIa3PMxG0NcdfC_WfyoY0KHc5X68lIUnzfwZGp2rfmQRrps57Ea6RiwxF1eheFqBBu1PbNz0dqob04HA56ZA84Ag6j0sJiJRPaRUy7zFi_ZGAnSgDOoE_MvXKM8u82qBAS04L5EOR2P0cfYjO3W9sCveyV4dRkajVcVF0jTlcpd0UeaUbuJrhNFfCEoJU2zCDCztqDWGmsOAJCZG-v14cwCDb8sjSk9lqPf6GvQ8OKv8-jcgb5u2v4oVUFawECOkgQVojZ7RGYRx2R9CKdjdF03qspJIDGtEEb3KV98oryCaHpnYQemoG-Z-yKpBYP4NGVLbAG3x1XpdJCF7RFUJz5_nM0BGMnJGZIHyMEoqBjZnB4xSJat3zvTKfZqhjZ_MncIu6DlvjVWKPbrhk-HFZ0bJPbLeJbbnYaziWwUt89w6-Prt80N2p9r5QlelhKDsqupTB9mV41Pn5z43WlXeYODJThvvObDlKal2vlk-xD3nTQT9V1TYoFljTtleaMMHAHsA3O-MjCHgG0Ig3CszcNNqlV-SU2Si4

### Roles
GET http://localhost/api/roles HTTP/1.1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmUzMTc0NmRkNThmMDMzMzM3ZWEwNWI2MGFjZGQyYmUxZjgxMzIyZDAzZWE2MWYzOWM4ZDNiODMyMDA5OWRhOGQzOTBkMjQ3OWQ5MjM4YjMiLCJpYXQiOjE2MDM0OTkyNzQsIm5iZiI6MTYwMzQ5OTI3NCwiZXhwIjoxNjM1MDM1Mjc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.W162AGQVxgZMEJySJFycs1Ncjm9GQCTjQpo9PEn-iYKrUIeRrTBYSBc3KKvswBl5lAEu6qNIhGRDV6saO7RBM0JqBKn1ZvlBdkhGcvEq5EwoLUEHmUin99EqAnXSV0IROGviwzISLCUIa3PMxG0NcdfC_WfyoY0KHc5X68lIUnzfwZGp2rfmQRrps57Ea6RiwxF1eheFqBBu1PbNz0dqob04HA56ZA84Ag6j0sJiJRPaRUy7zFi_ZGAnSgDOoE_MvXKM8u82qBAS04L5EOR2P0cfYjO3W9sCveyV4dRkajVcVF0jTlcpd0UeaUbuJrhNFfCEoJU2zCDCztqDWGmsOAJCZG-v14cwCDb8sjSk9lqPf6GvQ8OKv8-jcgb5u2v4oVUFawECOkgQVojZ7RGYRx2R9CKdjdF03qspJIDGtEEb3KV98oryCaHpnYQemoG-Z-yKpBYP4NGVLbAG3x1XpdJCF7RFUJz5_nM0BGMnJGZIHyMEoqBjZnB4xSJat3zvTKfZqhjZ_MncIu6DlvjVWKPbrhk-HFZ0bJPbLeJbbnYaziWwUt89w6-Prt80N2p9r5QlelhKDsqupTB9mV41Pn5z43WlXeYODJThvvObDlKal2vlk-xD3nTQT9V1TYoFljTtleaMMHAHsA3O-MjCHgG0Ig3CszcNNqlV-SU2Si4

### Role by ID
GET http://localhost/api/roles/1 HTTP/1.1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmUzMTc0NmRkNThmMDMzMzM3ZWEwNWI2MGFjZGQyYmUxZjgxMzIyZDAzZWE2MWYzOWM4ZDNiODMyMDA5OWRhOGQzOTBkMjQ3OWQ5MjM4YjMiLCJpYXQiOjE2MDM0OTkyNzQsIm5iZiI6MTYwMzQ5OTI3NCwiZXhwIjoxNjM1MDM1Mjc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.W162AGQVxgZMEJySJFycs1Ncjm9GQCTjQpo9PEn-iYKrUIeRrTBYSBc3KKvswBl5lAEu6qNIhGRDV6saO7RBM0JqBKn1ZvlBdkhGcvEq5EwoLUEHmUin99EqAnXSV0IROGviwzISLCUIa3PMxG0NcdfC_WfyoY0KHc5X68lIUnzfwZGp2rfmQRrps57Ea6RiwxF1eheFqBBu1PbNz0dqob04HA56ZA84Ag6j0sJiJRPaRUy7zFi_ZGAnSgDOoE_MvXKM8u82qBAS04L5EOR2P0cfYjO3W9sCveyV4dRkajVcVF0jTlcpd0UeaUbuJrhNFfCEoJU2zCDCztqDWGmsOAJCZG-v14cwCDb8sjSk9lqPf6GvQ8OKv8-jcgb5u2v4oVUFawECOkgQVojZ7RGYRx2R9CKdjdF03qspJIDGtEEb3KV98oryCaHpnYQemoG-Z-yKpBYP4NGVLbAG3x1XpdJCF7RFUJz5_nM0BGMnJGZIHyMEoqBjZnB4xSJat3zvTKfZqhjZ_MncIu6DlvjVWKPbrhk-HFZ0bJPbLeJbbnYaziWwUt89w6-Prt80N2p9r5QlelhKDsqupTB9mV41Pn5z43WlXeYODJThvvObDlKal2vlk-xD3nTQT9V1TYoFljTtleaMMHAHsA3O-MjCHgG0Ig3CszcNNqlV-SU2Si4

### Permissions
GET http://localhost/api/permissions HTTP/1.1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmUzMTc0NmRkNThmMDMzMzM3ZWEwNWI2MGFjZGQyYmUxZjgxMzIyZDAzZWE2MWYzOWM4ZDNiODMyMDA5OWRhOGQzOTBkMjQ3OWQ5MjM4YjMiLCJpYXQiOjE2MDM0OTkyNzQsIm5iZiI6MTYwMzQ5OTI3NCwiZXhwIjoxNjM1MDM1Mjc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.W162AGQVxgZMEJySJFycs1Ncjm9GQCTjQpo9PEn-iYKrUIeRrTBYSBc3KKvswBl5lAEu6qNIhGRDV6saO7RBM0JqBKn1ZvlBdkhGcvEq5EwoLUEHmUin99EqAnXSV0IROGviwzISLCUIa3PMxG0NcdfC_WfyoY0KHc5X68lIUnzfwZGp2rfmQRrps57Ea6RiwxF1eheFqBBu1PbNz0dqob04HA56ZA84Ag6j0sJiJRPaRUy7zFi_ZGAnSgDOoE_MvXKM8u82qBAS04L5EOR2P0cfYjO3W9sCveyV4dRkajVcVF0jTlcpd0UeaUbuJrhNFfCEoJU2zCDCztqDWGmsOAJCZG-v14cwCDb8sjSk9lqPf6GvQ8OKv8-jcgb5u2v4oVUFawECOkgQVojZ7RGYRx2R9CKdjdF03qspJIDGtEEb3KV98oryCaHpnYQemoG-Z-yKpBYP4NGVLbAG3x1XpdJCF7RFUJz5_nM0BGMnJGZIHyMEoqBjZnB4xSJat3zvTKfZqhjZ_MncIu6DlvjVWKPbrhk-HFZ0bJPbLeJbbnYaziWwUt89w6-Prt80N2p9r5QlelhKDsqupTB9mV41Pn5z43WlXeYODJThvvObDlKal2vlk-xD3nTQT9V1TYoFljTtleaMMHAHsA3O-MjCHgG0Ig3CszcNNqlV-SU2Si4

### Permission by ID
GET http://localhost/api/permissions/1 HTTP/1.1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmUzMTc0NmRkNThmMDMzMzM3ZWEwNWI2MGFjZGQyYmUxZjgxMzIyZDAzZWE2MWYzOWM4ZDNiODMyMDA5OWRhOGQzOTBkMjQ3OWQ5MjM4YjMiLCJpYXQiOjE2MDM0OTkyNzQsIm5iZiI6MTYwMzQ5OTI3NCwiZXhwIjoxNjM1MDM1Mjc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.W162AGQVxgZMEJySJFycs1Ncjm9GQCTjQpo9PEn-iYKrUIeRrTBYSBc3KKvswBl5lAEu6qNIhGRDV6saO7RBM0JqBKn1ZvlBdkhGcvEq5EwoLUEHmUin99EqAnXSV0IROGviwzISLCUIa3PMxG0NcdfC_WfyoY0KHc5X68lIUnzfwZGp2rfmQRrps57Ea6RiwxF1eheFqBBu1PbNz0dqob04HA56ZA84Ag6j0sJiJRPaRUy7zFi_ZGAnSgDOoE_MvXKM8u82qBAS04L5EOR2P0cfYjO3W9sCveyV4dRkajVcVF0jTlcpd0UeaUbuJrhNFfCEoJU2zCDCztqDWGmsOAJCZG-v14cwCDb8sjSk9lqPf6GvQ8OKv8-jcgb5u2v4oVUFawECOkgQVojZ7RGYRx2R9CKdjdF03qspJIDGtEEb3KV98oryCaHpnYQemoG-Z-yKpBYP4NGVLbAG3x1XpdJCF7RFUJz5_nM0BGMnJGZIHyMEoqBjZnB4xSJat3zvTKfZqhjZ_MncIu6DlvjVWKPbrhk-HFZ0bJPbLeJbbnYaziWwUt89w6-Prt80N2p9r5QlelhKDsqupTB9mV41Pn5z43WlXeYODJThvvObDlKal2vlk-xD3nTQT9V1TYoFljTtleaMMHAHsA3O-MjCHgG0Ig3CszcNNqlV-SU2Si4
