### Login
POST http://localhost/api/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email": "user@email.com",
    "password": "123456"
}

#######################
### Logged examples ###
#######################
@token = (use returned token here)

### User Information
GET http://localhost/api/user HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}

### Permissions
GET http://localhost/api/permissions HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

### Permission by ID
GET http://localhost/api/permissions/1 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

### Update Permission
PUT http://localhost/api/permissions/1 HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}

&item[title]=Administrator Access
&item[name]=admin

### Delete Permission
DELETE http://localhost/api/permissions/1 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}